export const jobs = [
  {
    title: "Sr. Full Stack Engineer",
    employmentType: "Full-time",
    companyName: "ConGlobal",
    location: "Florida, United States",
    locationType: "Hybrid",
    startDate: "June 2024",
    endDate: "",
    currentWork: true,
    technologies: [
      "ReactJS",
      "JavaScript",
      "TypeScript",
      "HTML5",
      "CSS3",
      "Node.js",
      "Ant Design",
      "GraphQL",
      "Git",
      "Redux Toolkit",
    ],
  },
  {
    title: "Full Stack Engineer",
    employmentType: "Full-time",
    companyName: "ConGlobal",
    location: "Florida, United States",
    locationType: "Hybrid",
    startDate: "Jul 2023",
    endDate: "May 2024",
    currentWork: false,
    technologies: [
      "ReactJS",
      "JavaScript",
      "TypeScript",
      "HTML5",
      "CSS3",
      "Node.js",
      "Ant Design",
      "GraphQL",
      "Git",
      "Redux Toolkit",
    ],
  },
  {
    title: "Full Stack Developer",
    employmentType: "Full-time",
    companyName: "Communication Concepts Integration",
    location: "Florida, United States",
    locationType: "Hybrid",
    startDate: "Feb 2023",
    endDate: "Jul 2023",
    currentWork: false,
    technologies: [
      "ReactJS",
      "JavaScript",
      "TypeScript",
      "HTML5",
      "CSS3",
      "Node.js",
      "Ant Design",
      "GraphQL",
      "Git",
      "Redux Toolkit",
    ],
  },
  {
    title: "Full Stack Developer",
    employmentType: "Full-time",
    companyName: "Mowi",
    location: "Montevideo, Uruguay",
    locationType: "Remote",
    startDate: "Oct 2022",
    endDate: "Feb 2023",
    currentWork: false,
    technologies: [
      "ReactJS",
      "TypeScript",
      "Ant Design",
      "HTML5",
      "CSS3",
      "Node.js",
      "Git",
    ],
  },
  {
    title: "Web Application Developer",
    employmentType: "",
    companyName: "Freelance",
    location: "",
    locationType: "",
    startDate: "Sep 2021",
    endDate: "Oct 2022",
    currentWork: false,
    technologies: [
      "ReactJS",
      "JavaScript",
      "TypeScript",
      "HTML5",
      "CSS3",
      "Node.js",
      "Ant Design",
      "Git",
    ],
  },
  {
    title: "Career Break",
    employmentType: "",
    companyName: "Relocation",
    location: "",
    locationType: "",
    startDate: "Jun 2021",
    endDate: "Aug 2021",
    currentWork: false,
    technologies: [],
  },
  {
    title: "Web Application Developer",
    employmentType: "Full-time",
    companyName: "XETID",
    location: "Havana, Cuba",
    locationType: "On-site",
    startDate: "Sep 2012",
    endDate: "Jun 2021",
    currentWork: false,
    technologies: [
      "ReactJS",
      "JavaScript",
      "HTML",
      "CSS",
      "Node.js",
      "Ant Design",
      "PHP",
      "PostgreSQL",
      "Perl",
    ],
  },
];
